diplom test
Kamatari-rin/java-explore-with-me pull request #4
Opened 2023-09-16 07:09 UTC by Kamatari-rin

2023-09-17 19:07 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Вижу изменения в stats-service в 2-х подмодулях client и dto, а в server ничего не меняется?
2) Давай @Schema освоим
3) Delete методы или ничего не возвращают обычно или удаленные объекты или boolean

на доработку =)

2023-09-17 19:07 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/dto/event/EventFullDto.java
> +    private Integer confirmedRequests;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Количество одобренных заявок на участие в данном событии", example = "5")
private final @PositiveOrZero

Давай попробуем описание при помощи аннотации Schema из swagger добавить к переменным

2023-09-17 19:07 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/dto/request/EventRequestStatusUpdateRequestDto.java
> +    public enum RequestUpdateStatus {
Я бы вынес вне класс енам

2023-09-17 19:07 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/dto/request/UpdateEventDto.java
> +    public enum StateAction {
Я бы вынес вне класс енам

2023-09-17 19:07 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CategoryServiceImpl.java
> +    public String delete(Long catId) {
String возвращать плохая идея, лучше boolean

2023-09-17 19:07 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CompilationServiceImpl.java
> +    public String delete(Long compId) {
Плохая идея String возвращать

2023-09-18 07:31 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/dto/compilation/NewCompilationDto.java
> +    private Set<Long> events;
Перенес ниже.

2023-09-18 08:04 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/dto/request/EventRequestStatusUpdateRequestDto.java
> +    public enum RequestUpdateStatus {
Вынес

2023-09-18 08:31 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/dto/request/UpdateEventDto.java
> +    public enum StateAction {
Вынес

2023-09-18 08:33 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CategoryServiceImpl.java
> +    public String delete(Long catId) {
+

2023-09-18 08:33 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CompilationServiceImpl.java
> +    public String delete(Long compId) {
+

2023-09-20 06:00 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/dto/event/EventFullDto.java
> +    private Integer confirmedRequests;
Попробовал разобраться. Сделал для примера в классе EventFullDto, если все верно, то доделаю в остальных.

2023-09-20 06:26 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/EwmServiceApplication.java
> +@SpringBootApplication(scanBasePackages = {"ru.practicum"})
Без этого не получается найти бин StatsClient в EventServiceImpl.

2023-09-21 08:20 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

Schema корректно применена

2023-09-21 08:20 UTC, krylov-sergey-sergeevich commented on pom.xml
> +					<groupId>org.springdoc</groupId>
Отличное решение

2023-09-21 10:13 UTC, merged