Feature comments
Kamatari-rin/java-explore-with-me pull request #5
Opened 2023-09-23 19:54 UTC by Kamatari-rin

2023-09-26 06:38 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Логов маловато
2) Почему @Schema удалены?

Давай чутка докрутим =)

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on README.md
> +https://github.com/Kamatari-rin/java-explore-with-me/pull/5
Давай сформируем красивое описание:

- В чем смысл проекта
- Какой стек был использован
- Как запускается проект
- Кто автор
- Схему бд можно или картинку архитектуры если есть желание

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/controller/comment/CommentControllerAdmin.java
> +    public void delete(@RequestParam @Positive Long commentId) {
Почему выбран @RequestParam а не PathVariable

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/entity/Comment.java
> +    @Column(name = "content")
я бы еще тут length указал бы

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/repository/EventRepository.java
> +//    @Query("SELECT e " +
Закомментированный код лучше удалять если не нужен

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CommentServiceImpl.java
> +            throw new ValidationException(String.format("User %s isn't author of comment %s ", authorId, commentId));
Тут Security исключение как будто бы, а не валидации

2023-09-26 06:38 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CommentServiceImpl.java
> +            throw new ValidationException(String.format("User %s isn't author of comment %s", authorId, commentId));
SecurityException

2023-09-26 08:07 UTC, Kamatari-rin commented on README.md
> +https://github.com/Kamatari-rin/java-explore-with-me/pull/5
Добавил

2023-09-26 08:07 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/repository/EventRepository.java
> +//    @Query("SELECT e " +
да, забыл удалить

2023-09-26 08:09 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CommentServiceImpl.java
> +            throw new ValidationException(String.format("User %s isn't author of comment %s ", authorId, commentId));
+

2023-09-26 08:09 UTC, Kamatari-rin commented on ewm-service/src/main/java/ru/practicum/main/service/impl/CommentServiceImpl.java
> +            throw new ValidationException(String.format("User %s isn't author of comment %s", authorId, commentId));
изменил

2023-09-26 08:43 UTC, Kamatari-rin commented on README.md
> +https://github.com/Kamatari-rin/java-explore-with-me/pull/5
Добавил логи в контроллеры.
@Schema заваливала тесты на гитхаб хотя при запуске на пк все было нормально, так как сроки поджимают решил отказаться и разобраться потом в чем проблема.

2023-09-27 06:02 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

-------------------------------

Ну все наше взаимодействие подходит к концу, желаю удачи с защитой и в работе!

Если будет  желание общаться, работать вместе или обсудить интересный пет-проект, я всегда открыт для этого, мои контакты:
тг https://t.me/kssergey
инста мои заметки по it: https://instagram.com/krylov.tech

2023-10-28 09:37 UTC, merged